feat: bootloader new features, logic adjustments
OneKeyHQ/firmware pull request #406
Opened 2023-05-31 05:06 UTC by 424778940z

This PR contains following:

Bootloader new features, UI and logic improvements
HAL related changes that required by new bootloader features or logic changes
Command line tool new features
Debugger scripts updates

2023-05-31 06:45 UTC, loatheb requested changes

2023-05-31 06:45 UTC, loatheb commented on common/protob/messages-bootloader.proto
> +    optional bool force_erase = 3;
这里这个参数让 SDK 控制是为了什么？有哪些场景会用到这个

2023-05-31 06:45 UTC, loatheb commented on core/embed/trezorhal/nordic_dfu.c
> +    ble_usart_irq_disable();
这里关于 ble 的改动是也会影响整个的蓝牙升级流程吗？还是说只影响 DFU 的不影响目前我们 APP 使用的蓝牙流程

2023-05-31 06:45 UTC, loatheb commented on core/embed/bootloader/bootui.c
> +          uint16_t width = progress *10 * 360 / 1000;
`progress *10` 这里有个 lint 问题

2023-05-31 07:08 UTC, 424778940z commented on common/protob/messages-bootloader.proto
> +    optional bool force_erase = 3;
上面的注释就是解释这个参数是干嘛用的
这个参数如果设置为true就会跳过降级和vendor改变的判定, 直接认为需要重置设备 (注意, 用户仍然需要确认才会进行下一步)

2023-05-31 07:10 UTC, loatheb commented on common/protob/messages-bootloader.proto
> +    optional bool force_erase = 3;
目前是哪个场景需要传入这个参数？还是说只是为了以后来使用，并没有实际的场景需要用到这个

2023-05-31 07:11 UTC, 424778940z commented on core/embed/trezorhal/nordic_dfu.c
> +    ble_usart_irq_disable();
都不会, 之前的函数一个都没改, 老的流程用到的东西基本没有影响
这个函数只是重启蓝牙芯片固件用的, 蓝牙升级之后还在dfu不会重启
老流程升级蓝牙直接重启机器所以不需要单独重启蓝牙
新流程允许升级蓝牙之后回主页继续升级其他东西, 所以需要单独重启一下蓝牙以不重启的前提下保证功能正常

2023-05-31 07:27 UTC, 424778940z commented on core/embed/bootloader/bootui.c
> +          uint16_t width = progress *10 * 360 / 1000;
minor, 不影响结果, 改了, force push了

2023-06-01 09:20 UTC, loatheb approved these changes, later dismissed

2023-06-01 11:21 UTC, lihuanhuan reviewed
修复一下style的报错

2023-06-02 07:22 UTC, loatheb approved these changes

2023-06-02 07:22 UTC, loatheb approved these changes

2023-06-02 07:55 UTC, lihuanhuan approved these changes

2023-06-02 07:55 UTC, merged